version: "3.0"

networks:
  small-glade-network:
    driver: bridge

services:
  app:
    build: "./"
    command: ["npm", "start"]
    environment:
      - PORT=1234
      - TILE_SIZE=${TILE_SIZE:-80}
    networks:
      - small-glade-network
    ports:
      - "4989:1234"
    volumes:
      - ./:/home/node/application/app:delegated
      - /home/node/application/app/dist/
      - /home/node/application/app/node_modules/
