version: "3.0"

networks:
  small-glade-network:
    driver: bridge

services:
  app:
    build: "./"
    command: ["npm", "start"]
    environment:
      - PORT=1234
      - TILE_SIZE=${TILE_SIZE:-80}
      - VITALS_FULLNESS_HEALTH_LOSS_PER_TURN=${VITALS_FULLNESS_HEALTH_LOSS_PER_TURN:-5}
      - VITALS_FULLNESS_LOSS_PER_TURN=${VITALS_FULLNESS_LOSS_PER_TURN:-1}
      - VITALS_HYDRATION_HEALTH_LOSS_PER_TURN=${VITALS_HYDRATION_HEALTH_LOSS_PER_TURN:-10}
      - VITALS_HYDRATION_LOSS_PER_TURN=${VITALS_HYDRATION_LOSS_PER_TURN:-4}
      - VITALS_WARMTH_HEALTH_LOSS_PER_TURN=${VITALS_WARMTH_HEALTH_LOSS_PER_TURN:-10}
      - VITALS_WARMTH_LOSS_PER_TURN=${VITALS_WARMTH_LOSS_PER_TURN:-5}
      - WEATHER_TEMPERATURE_LIMIT_LOWER=${WEATHER_TEMPERATURE_LIMIT_LOWER:--20}
      - WEATHER_TEMPERATURE_LIMIT_UPPER=${WEATHER_TEMPERATURE_LIMIT_UPPER:-1}
    networks:
      - small-glade-network
    ports:
      - "4989:1234"
    volumes:
      - ./:/home/node/application/app:delegated
      - /home/node/application/app/dist/
      - /home/node/application/app/node_modules/
