name: Deploy
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build

      - name: FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          dangerous-clean-slate: true
          local-dir: ./dist/
          password: ${{ secrets.FTP_PASSWORD }}
          server: ftp.hvolschenk.co.za
          username: ${{ secrets.FTP_USERNAME }}
