name: Pull request
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Test vulnerabilities
        run: npm run test:vulnerabilities

      - name: Test formatting
        run: npm run test:format
      
      - name: Test linting
        run: npm run test:lint
      
      - name: Test types
        run: npm run test:types
      
      - name: Test (Unit)
        run: npm run test:scripts
